server:
  port: ${PORT:8085}

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: core-service
          uri: lb://CORE-SERVICE
          predicates:
            - Path=/core/**
          filters:
            - AuthenticationFilter
  application:
    name: EMAIL_MARKETING_TOOL

eureka:
  client:
    service-url:
      defaultZone : ${EUREKA_CLIENT_URL:http://localhost:8762/eureka/}